version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb24
    ports:
      - "27017:27017"
    volumes:
      - /home/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network
  
  express-app:
    build:
      context: ./app
      dockerfile: dockerfile
    environment:
      - DB_CONNECTION_STRING=mongodb://root:mongodb24@mongo:27017/vr?authSource=admin
    ports:
      - "3000:3000"
    networks:
      - mongo-compose-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.pem:/etc/nginx/cert.pem
      - ./nginx/key.pem:/etc/nginx/key.pem
    networks:
      - mongo-compose-network

networks: 
  mongo-compose-network:
    driver: bridge
